import type { Meta, StoryObj } from '@storybook/nextjs-vite';
import type { L4ProxyHost } from '../../src/lib/models/l4-proxy-hosts';
import L4ProxyHostsClient from '../../app/(dashboard)/l4-proxy-hosts/L4ProxyHostsClient';
import { withDashboardLayout } from '../decorators';

const meta: Meta<typeof L4ProxyHostsClient> = {
  title: 'Pages/L4 Proxy Hosts',
  component: L4ProxyHostsClient,
  decorators: [withDashboardLayout],
  parameters: {
    layout: 'fullscreen',
    nextjs: { appDirectory: true, navigation: { pathname: '/l4-proxy-hosts' } },
  },
};

export default meta;
type Story = StoryObj<typeof L4ProxyHostsClient>;

const now = new Date().toISOString();

const mockHosts: L4ProxyHost[] = [
  {
    id: 1,
    name: 'Game Server',
    protocol: 'tcp',
    listen_address: ':25565',
    upstreams: ['10.0.0.2:25565'],
    matcher_type: 'tls_sni',
    matcher_value: ['minecraft.example.com'],
    tls_termination: true,
    proxy_protocol_version: null,
    proxy_protocol_receive: false,
    enabled: true,
    meta: null,
    load_balancer: {
      enabled: true,
      policy: 'round_robin',
      tryDuration: '30s',
      tryInterval: '250ms',
      retries: 3,
      activeHealthCheck: null,
      passiveHealthCheck: null,
    },
    dns_resolver: null,
    upstream_dns_resolution: null,
    geoblock: null,
    geoblock_mode: 'merge',
    created_at: now,
    updated_at: now,
  },
  {
    id: 2,
    name: 'DNS Forwarder',
    protocol: 'udp',
    listen_address: ':5353',
    upstreams: ['10.0.0.53:53', '10.0.0.54:53'],
    matcher_type: 'none',
    matcher_value: [],
    tls_termination: false,
    proxy_protocol_version: null,
    proxy_protocol_receive: false,
    enabled: true,
    meta: null,
    load_balancer: null,
    dns_resolver: {
      enabled: true,
      resolvers: ['1.1.1.1:53', '8.8.8.8:53'],
      fallbacks: [],
      timeout: '5s',
    },
    upstream_dns_resolution: null,
    geoblock: null,
    geoblock_mode: 'merge',
    created_at: now,
    updated_at: now,
  },
  {
    id: 3,
    name: 'Mail Relay',
    protocol: 'tcp',
    listen_address: ':587',
    upstreams: ['mail.internal:587'],
    matcher_type: 'none',
    matcher_value: [],
    tls_termination: false,
    proxy_protocol_version: 'v1',
    proxy_protocol_receive: false,
    enabled: true,
    meta: null,
    load_balancer: null,
    dns_resolver: null,
    upstream_dns_resolution: null,
    geoblock: {
      enabled: true,
      block_countries: ['CN', 'RU', 'KP'],
      block_continents: [],
      block_asns: [],
      block_cidrs: [],
      block_ips: [],
      allow_countries: [],
      allow_continents: [],
      allow_asns: [],
      allow_cidrs: [],
      allow_ips: [],
    },
    geoblock_mode: 'merge',
    created_at: now,
    updated_at: now,
  },
  {
    id: 4,
    name: 'Database Proxy',
    protocol: 'tcp',
    listen_address: ':5432',
    upstreams: ['db-primary:5432', 'db-replica-1:5432', 'db-replica-2:5432'],
    matcher_type: 'none',
    matcher_value: [],
    tls_termination: true,
    proxy_protocol_version: null,
    proxy_protocol_receive: false,
    enabled: true,
    meta: null,
    load_balancer: null,
    dns_resolver: null,
    upstream_dns_resolution: {
      enabled: true,
      family: 'ipv4',
    },
    geoblock: null,
    geoblock_mode: 'merge',
    created_at: now,
    updated_at: now,
  },
  {
    id: 5,
    name: 'VPN Tunnel',
    protocol: 'tcp',
    listen_address: ':1194',
    upstreams: ['10.0.1.10:1194'],
    matcher_type: 'tls_sni',
    matcher_value: ['vpn.example.com'],
    tls_termination: true,
    proxy_protocol_version: null,
    proxy_protocol_receive: false,
    enabled: true,
    meta: null,
    load_balancer: null,
    dns_resolver: {
      enabled: true,
      resolvers: ['10.0.0.1:53'],
      fallbacks: [],
      timeout: '3s',
    },
    upstream_dns_resolution: {
      enabled: true,
      family: 'ipv4',
    },
    geoblock: {
      enabled: true,
      block_countries: [],
      block_continents: [],
      block_asns: [],
      block_cidrs: ['0.0.0.0/0'],
      block_ips: [],
      allow_countries: ['US', 'GB', 'DE', 'FR'],
      allow_continents: [],
      allow_asns: [],
      allow_cidrs: [],
      allow_ips: [],
    },
    geoblock_mode: 'override',
    created_at: now,
    updated_at: now,
  },
  {
    id: 6,
    name: 'Legacy SMTP',
    protocol: 'tcp',
    listen_address: ':25',
    upstreams: ['legacy-mail:25'],
    matcher_type: 'none',
    matcher_value: [],
    tls_termination: false,
    proxy_protocol_version: null,
    proxy_protocol_receive: false,
    enabled: false,
    meta: null,
    load_balancer: null,
    dns_resolver: null,
    upstream_dns_resolution: null,
    geoblock: null,
    geoblock_mode: 'merge',
    created_at: now,
    updated_at: now,
  },
];

export const Default: Story = {
  name: 'L4 Hosts — full list',
  args: {
    hosts: mockHosts,
    pagination: { total: 6, page: 1, perPage: 25 },
    initialSearch: '',
    initialSort: { sortBy: 'name', sortDir: 'asc' },
  },
};
