import type { Meta, StoryObj } from '@storybook/nextjs-vite';
import { within, userEvent, expect } from 'storybook/test';
import type { ProxyHost } from '../../src/lib/models/proxy-hosts';
import type { RuleSetItem } from '../../src/components/waf/RuleSetDialog';
import ProxyHostsClient from '../../app/(dashboard)/proxy-hosts/ProxyHostsClient';
import { withDashboardLayout } from '../decorators';

const meta: Meta<typeof ProxyHostsClient> = {
  title: 'Pages/Proxy Hosts',
  component: ProxyHostsClient,
  decorators: [withDashboardLayout],
  parameters: {
    layout: 'fullscreen',
    nextjs: { appDirectory: true, navigation: { pathname: '/proxy-hosts' } },
  },
};

export default meta;
type Story = StoryObj<typeof ProxyHostsClient>;

const now = new Date().toISOString();

const mockRuleSets: RuleSetItem[] = [
  {
    id: 10,
    name: 'WordPress Relaxation',
    description: 'Relaxes OWASP CRS rules for WordPress admin and REST API.',
    directives: 'SecRuleRemoveById 941100',
    isPreset: true,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 11,
    name: 'Django / Python API',
    description: 'Relaxes rules triggered by Django REST Framework.',
    directives: 'SecRuleRemoveById 920420',
    isPreset: true,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 12,
    name: 'My Super Long Custom Rule Set Name That Exceeds Normal Lengths',
    description: null,
    directives: 'SecRule ARGS "evil" "id:9001,deny"',
    isPreset: false,
    createdAt: now,
    updatedAt: now,
  },
];

const mockHosts: ProxyHost[] = [
  {
    id: 1,
    name: 'Main App',
    domains: ['app.example.com'],
    upstreams: ['backend:3000'],
    certificate_id: 1,
    access_list_id: null,
    ssl_forced: true,
    hsts_enabled: true,
    hsts_subdomains: false,
    allow_websocket: true,
    preserve_host_header: true,
    skip_https_hostname_validation: false,
    enabled: true,
    created_at: now,
    updated_at: now,
    custom_reverse_proxy_json: null,
    custom_pre_handlers_json: null,
    authentik: null,
    load_balancer: null,
    dns_resolver: null,
    upstream_dns_resolution: null,
    geoblock: null,
    geoblock_mode: 'merge',
    waf: { enabled: true, mode: 'On', load_owasp_crs: true, waf_mode: 'merge' },
    mtls: null,
    redirects: [],
    rewrite: null,
  },
  {
    id: 2,
    name: 'Admin Panel',
    domains: ['admin.example.com'],
    upstreams: ['admin-service:8080'],
    certificate_id: 1,
    access_list_id: 1,
    ssl_forced: true,
    hsts_enabled: true,
    hsts_subdomains: false,
    allow_websocket: false,
    preserve_host_header: false,
    skip_https_hostname_validation: false,
    enabled: true,
    created_at: now,
    updated_at: now,
    custom_reverse_proxy_json: null,
    custom_pre_handlers_json: null,
    authentik: null,
    load_balancer: null,
    dns_resolver: null,
    upstream_dns_resolution: null,
    geoblock: null,
    geoblock_mode: 'merge',
    waf: null,
    mtls: { enabled: true, ca_certificate_ids: [1] },
    redirects: [],
    rewrite: null,
  },
  {
    id: 3,
    name: 'Public API',
    domains: ['api.example.com', 'api-v2.example.com'],
    upstreams: ['api:4000'],
    certificate_id: 2,
    access_list_id: null,
    ssl_forced: true,
    hsts_enabled: true,
    hsts_subdomains: false,
    allow_websocket: false,
    preserve_host_header: false,
    skip_https_hostname_validation: false,
    enabled: true,
    created_at: now,
    updated_at: now,
    custom_reverse_proxy_json: null,
    custom_pre_handlers_json: null,
    authentik: null,
    load_balancer: null,
    dns_resolver: null,
    upstream_dns_resolution: null,
    geoblock: {
      enabled: true,
      block_countries: ['KP'],
      block_continents: [],
      block_asns: [],
      block_cidrs: [],
      block_ips: [],
      allow_countries: [],
      allow_continents: [],
      allow_asns: [],
      allow_cidrs: [],
      allow_ips: [],
      redirect_url: null,
      response_body: 'Forbidden',
    } as ProxyHost['geoblock'],
    geoblock_mode: 'override',
    waf: { enabled: true, mode: 'On', load_owasp_crs: true, custom_directives: '# custom rules', waf_mode: 'override' },
    mtls: null,
    redirects: [],
    rewrite: { path_prefix: '/api/v1' },
  },
  {
    id: 7,
    name: 'WordPress Blog',
    domains: ['blog.example.com'],
    upstreams: ['wordpress:80'],
    certificate_id: 1,
    access_list_id: null,
    ssl_forced: true,
    hsts_enabled: false,
    hsts_subdomains: false,
    allow_websocket: false,
    preserve_host_header: false,
    skip_https_hostname_validation: false,
    enabled: true,
    created_at: now,
    updated_at: now,
    custom_reverse_proxy_json: null,
    custom_pre_handlers_json: null,
    authentik: null,
    load_balancer: null,
    dns_resolver: null,
    upstream_dns_resolution: null,
    geoblock: null,
    geoblock_mode: 'merge',
    waf: { enabled: true, mode: 'On', load_owasp_crs: true, waf_mode: 'merge', rule_set_ids: [10] },
    mtls: null,
    redirects: [],
    rewrite: null,
  },
  {
    id: 8,
    name: 'Multi-RuleSet App',
    domains: ['multi.example.com'],
    upstreams: ['multi:3000'],
    certificate_id: 1,
    access_list_id: null,
    ssl_forced: true,
    hsts_enabled: false,
    hsts_subdomains: false,
    allow_websocket: false,
    preserve_host_header: false,
    skip_https_hostname_validation: false,
    enabled: true,
    created_at: now,
    updated_at: now,
    custom_reverse_proxy_json: null,
    custom_pre_handlers_json: null,
    authentik: null,
    load_balancer: null,
    dns_resolver: null,
    upstream_dns_resolution: null,
    geoblock: null,
    geoblock_mode: 'merge',
    waf: { enabled: true, mode: 'On', load_owasp_crs: true, waf_mode: 'merge', rule_set_ids: [10, 11, 12] },
    mtls: null,
    redirects: [],
    rewrite: null,
  },
  {
    id: 4,
    name: 'Scale Service',
    domains: ['scale.example.com'],
    upstreams: ['node-1:3000', 'node-2:3000', 'node-3:3000'],
    certificate_id: 3,
    access_list_id: null,
    ssl_forced: true,
    hsts_enabled: false,
    hsts_subdomains: false,
    allow_websocket: true,
    preserve_host_header: true,
    skip_https_hostname_validation: false,
    enabled: true,
    created_at: now,
    updated_at: now,
    custom_reverse_proxy_json: null,
    custom_pre_handlers_json: null,
    authentik: {
      enabled: true,
      outpostDomain: 'auth.example.com',
      outpostUpstream: 'authentik:9000',
      authEndpoint: null,
      copyHeaders: ['X-authentik-username', 'X-authentik-groups'],
      trustedProxies: ['10.0.0.0/8'],
      setOutpostHostHeader: true,
      protectedPaths: null,
    },
    load_balancer: {
      enabled: true,
      policy: 'round_robin',
      policyHeaderField: null,
      policyCookieName: null,
      policyCookieSecret: null,
      tryDuration: '30s',
      tryInterval: '250ms',
      retries: 3,
      activeHealthCheck: {
        enabled: true,
        uri: '/health',
        port: null,
        interval: '10s',
        timeout: '5s',
        status: 200,
        body: null,
      },
      passiveHealthCheck: null,
    },
    dns_resolver: {
      enabled: true,
      resolvers: ['10.0.0.1:53'],
      fallbacks: null,
      timeout: '5s',
    },
    upstream_dns_resolution: null,
    geoblock: null,
    geoblock_mode: 'merge',
    waf: null,
    mtls: null,
    redirects: [],
    rewrite: null,
  },
  {
    id: 5,
    name: 'Legacy Redirect',
    domains: ['old.example.com'],
    upstreams: [],
    certificate_id: null,
    access_list_id: null,
    ssl_forced: false,
    hsts_enabled: false,
    hsts_subdomains: false,
    allow_websocket: false,
    preserve_host_header: false,
    skip_https_hostname_validation: false,
    enabled: true,
    created_at: now,
    updated_at: now,
    custom_reverse_proxy_json: null,
    custom_pre_handlers_json: null,
    authentik: null,
    load_balancer: null,
    dns_resolver: null,
    upstream_dns_resolution: null,
    geoblock: null,
    geoblock_mode: 'merge',
    waf: null,
    mtls: null,
    redirects: [
      { from: '/', to: 'https://app.example.com', status: 301 },
    ],
    rewrite: null,
  },
  {
    id: 6,
    name: 'Staging',
    domains: ['staging.example.com'],
    upstreams: ['staging:3000'],
    certificate_id: null,
    access_list_id: null,
    ssl_forced: false,
    hsts_enabled: false,
    hsts_subdomains: false,
    allow_websocket: false,
    preserve_host_header: false,
    skip_https_hostname_validation: false,
    enabled: false,
    created_at: now,
    updated_at: now,
    custom_reverse_proxy_json: null,
    custom_pre_handlers_json: null,
    authentik: null,
    load_balancer: null,
    dns_resolver: null,
    upstream_dns_resolution: null,
    geoblock: null,
    geoblock_mode: 'merge',
    waf: null,
    mtls: null,
    redirects: [],
    rewrite: null,
  },
];

export const Default: Story = {
  name: 'Proxy Hosts — full list',
  args: {
    hosts: mockHosts,
    certificates: [],
    accessLists: [],
    caCertificates: [],
    authentikDefaults: null,
    pagination: { total: mockHosts.length, page: 1, perPage: 25 },
    initialSearch: '',
    initialSort: { sortBy: 'name', sortDir: 'asc' },
    ruleSets: mockRuleSets,
  },
};

/**
 * Verifies the sticky actions column is reachable at narrow desktop widths
 * (768–1000 px) where the table overflows horizontally.
 */
export const StickyActionsNarrow: Story = {
  name: '▶ Sticky actions — narrow desktop',
  args: {
    ...Default.args,
  },
  globals: {
    viewport: { value: 'narrow-desktop' },
  },
  decorators: [withDashboardLayout],
  play: async ({ canvasElement }) => {
    const canvas = within(canvasElement);

    // The actions menu buttons should be visible and clickable even at 800px
    const menuButtons = canvas.getAllByRole('button', { name: /open menu/i });
    expect(menuButtons.length).toBeGreaterThan(0);

    // Click the first "..." menu — it should open the dropdown
    await userEvent.click(menuButtons[0]);

    // Radix DropdownMenu portals to document.body, not inside canvasElement
    const body = within(document.body);
    const editItem = await body.findByRole('menuitem', { name: /edit/i });
    expect(editItem).toBeTruthy();

    // Close by pressing Escape
    await userEvent.keyboard('{Escape}');
  },
};
